# Generated by Django 3.2.3 on 2021-05-26 20:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('genre', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=303, size=3)),
                ('platform', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('episode', models.IntegerField()),
            ],
        ),
    ]
