# Generated by Django 3.2.3 on 2021-05-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_shows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
